Feature/weather
Pavel-Spitsin-s/bot_helper pull request #2
Opened 2022-12-19 09:36 UTC by nekstas

Добавлены функции для работы с API геокодера, Яндекс.Погоды и некоторые вспомогательные функции.
Также частично есть файлик с обработчиком запроса погоды, но, кажется, его рано добавлять, пока нет классификатора интентов и таггера.

2022-12-19 12:15 UTC, russab0 commented on api/static_maps.py
> +    return STATIC_MAPS_URL + \
Для этого есть красивая функция urllib.parse.urlencode

2022-12-19 12:15 UTC, russab0 commented on api/weather.py
> +conditions = {'clear': 'ясно', 'partly-cloudy': 'малооблачно', 'cloudy': 'облачно с прояснениями',
После `= {'` лучше сделать перевод строки

2022-12-19 12:15 UTC, russab0 commented on api/weather.py
> +    b['дата'] = datetime.datetime.fromtimestamp(res['now'])
Ключи на латинице лучше не использовать

2022-12-19 14:39 UTC, russab0 commented
И .env тоже надо убрать

2022-12-19 19:54 UTC, nekstas commented
> И .env тоже надо убрать

Его же и так нет

2022-12-20 19:36 UTC, russab0 requested changes

2022-12-20 19:36 UTC, russab0 commented on api/weather.py
> +    b['tempreture'] = dan['temp']
temperature

2022-12-20 19:36 UTC, russab0 commented on api/weather.py
> +    b['smile'] = CONDITION_TO_SMILE[dan['condition']]
smile -> emoji

2022-12-20 19:36 UTC, russab0 commented on api/weather.py
> +        b['pressure'] = dan[i]['parts']['day_short']['pressure_mm']
Код в  `get_today_weather` и `obr_forecasts` сильно дублируется. Мб выделить общую часть в отдельную функцию?

2022-12-20 19:36 UTC, russab0 commented on api/weather.py
> +        b['wind_deer'] = wind_dirs[s]
Если тут про направление ветра, то правильно `wind_dir` (wind direction)

2022-12-21 11:33 UTC, russab0 approved these changes

2022-12-21 11:34 UTC, merged