ADD ALL
Pavel-Spitsin-s/bot_helper pull request #3
Opened 2022-12-19 11:12 UTC by WannaSleep43

2022-12-19 11:48 UTC, nekstas commented on .env
> -# DO NOT ADD THIS FILE TO VERSION CONTROL!
Может, эти файлы вернуть?

2022-12-19 11:48 UTC, nekstas commented on Makefile
> -	| more $(shell test $(shell uname) = Darwin && echo '--no-init --raw-control-chars')
Может, эти файлы вернуть?

2022-12-19 11:48 UTC, nekstas commented on README.md
> -
Может, эти файлы вернуть?

2022-12-19 11:48 UTC, nekstas commented on TextToSpeech.py
> +device = torch.device('cpu')
Может, получать CPU или GPU из env?

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +db_sess = db_session.create_session()
Плохая идея создавать глобальную сессию

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +    file = csv.reader(open('data/not using data/jokes.csv'))
Что за папка `not using data`? Может, лучше какое-нибудь другое название?

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +def fillJokes():
В Python используется `snake_case` же

2022-12-19 11:48 UTC, nekstas commented on classifier.py
> +from intents import JokesGen, SelectFilm, SelectSeries, LastNews
Кажется, что файлы называть в верхнем регистре тоже не очень хорошая идея

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +    file = csv.reader(open('data/not using data/films.csv'))
Что за папка not using data? Может, лучше какое-нибудь другое название

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +    file = csv.reader(open('data/not using data/series.csv'))
Что за папка not using data? Может, лучше какое-нибудь другое название

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +        jid += 1
Дублирование кода, нужна бы отдельная функция

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +def fillFilms():
`snake_case`

2022-12-19 11:48 UTC, nekstas commented on data/fill.py
> +def fillSeries():
`snake_case`

2022-12-19 11:48 UTC, nekstas commented on data/models/db_session.py
> +    global __factory
Глобальные переменные - зло

2022-12-19 11:48 UTC, nekstas commented on intents/JokesGen.py
> +import sqlite3
Опять названия файлов в верхнем регистре

2022-12-19 11:48 UTC, nekstas commented on intents/JokesGen.py
> +        return get_joke()
Можно оптимизировать:
```python
def get_joke():
    if not joke_list:
        for i in range(100):
            id_ = randint(1, 17078)  # range id
            text = db_sess.query(joke.Joke).filter(joke.Joke.id == id_).first().text
            joke_list.append(text)
    res = joke_list[-1]
    joke_list.pop()
    return res
```

2022-12-19 11:48 UTC, nekstas commented on intents/LastNews.py
> +    link = 'https://ria.ru/'
Лучше вынести за функцию, например, в начало файла

2022-12-19 11:48 UTC, nekstas commented on intents/LastNews.py
> +    req = requests.get(link)
У нас бот будет написан с использованием асинхронной библиотеки, поэтому нам нужен не `requests`, а `aiohttp`.

2022-12-19 11:48 UTC, nekstas commented on intents/JokesGen.py
> +            ID = randint(1, 17078)  # range id
Лучше использовать функции из SQLAlchemy для получения рандомных записей.

2022-12-19 11:48 UTC, nekstas commented on intents/SelectFilm.py
> +MAXID_FILM = 998
Что это вообще такое?)

2022-12-19 11:48 UTC, nekstas commented on intents/SelectFilm.py
> +    rand_id = randint(0, MAXID_FILM)
Лучше использовать функции из SQLAlchemy для получения рандомных записей.

2022-12-19 11:48 UTC, nekstas commented on intents/SelectSeries.py
> +MAXID_SERIES = 472
Тоже костыль, нужно выбирать рандомную запись из БД другим образом

2022-12-19 11:48 UTC, nekstas commented on intents/SelectSeries.py
> +    rand_id = randint(0, MAXID_SERIES)
Лучше использовать функции из SQLAlchemy для получения рандомных записей.

2022-12-19 11:48 UTC, nekstas commented on models/small model/README
> +Small Russian model for Vosk (Android, RPi, other small devices)
Может, убрать пробелы в названии папки `small model`

2022-12-19 11:48 UTC, nekstas commented on using_db.py
> +db_sess = db_session.create_session()
Зачем создавать сессию в этом месте, а не в функциях, где она нужна?

2022-12-19 11:48 UTC, nekstas commented on using_db.py
> +    user_ = db_sess.query(user.User).filter(user.User.tg_id == tgid).one_or_none()
Нижнее подчёркивание в `user_` не нужно, так как `user` не встроенные в Python функция, класс и т. п.

2022-12-19 11:58 UTC, WannaSleep43 commented on using_db.py
> +db_sess = db_session.create_session()
Кажется, что так удобнее и мб так будет одна сессия передаваться, а не каждый раз новая создаваться

2022-12-20 06:45 UTC, nekstas commented on using_db.py
> +db_sess = db_session.create_session()
Теоретически, так не очень хорошо)

2022-12-20 19:36 UTC, russab0 requested changes

2022-12-20 19:36 UTC, russab0 commented on .env
> -# DO NOT ADD THIS FILE TO VERSION CONTROL!
.env файла точно не должно быть в репозитории

2022-12-20 19:36 UTC, russab0 commented on .env
> -# DO NOT ADD THIS FILE TO VERSION CONTROL!
А остальное можно по желанию вернуть)

2022-12-20 19:36 UTC, russab0 commented on SpeechToText.py
> +from aiogram import types
Название файла лучше писать snake_case'ом: speech_to_text.py или speech2text.py

2022-12-20 19:36 UTC, russab0 commented on TextToSpeech.py
> +device = torch.device('cpu')
Обычно всегда используют cuda, если он доступен. А если нет, то можно и cpu:
`device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')`

2022-12-20 19:36 UTC, russab0 commented on TextToSpeech.py
> +model, _ = torch.hub.load(repo_or_dir='snakers4/silero-models', model='silero_tts',
Строки 'snakers4/silero-models' и 'silero_tts' лучше вынести в контстанты

2022-12-20 19:36 UTC, russab0 commented on TextToSpeech.py
> +language = 'ru'
Константы обычно пишутся большими буквами: LANGUAGE, MODEL_ID

2022-12-20 19:36 UTC, russab0 commented on classifier.py
> +from intents import JokesGen, SelectFilm, SelectSeries, LastNews
+

2022-12-20 19:36 UTC, russab0 commented on data/fill.py
> +        jid += 1
Дико плюсую

2022-12-22 07:52 UTC, russab0 requested changes

2022-12-22 07:52 UTC, russab0 commented on data/models/reminder.py
> +    user = orm.relation('User')
А неужели нужно и user, и user_id?

2022-12-22 07:52 UTC, russab0 commented on intents/add_reminder.py
> +    reminder = Reminder()
А нельзя передать user, target_time, action прямо при создании объекта класса Reminder?

2022-12-22 07:52 UTC, russab0 commented on intents/talking.py
> +    # last = db_sess.query(Message).filter(Message.user_id == user.id and Message.intent == 'болталка').all()[-1:]
Давайте без комментов, которые скрывают код)

2022-12-22 07:52 UTC, russab0 commented on intents/talking.py
> +    for i in s.split('@@ПЕРВЫЙ@@'):
i, j - обычно числа-индексы, а тут это строки-элементы, лучше использовать другое название переменной

2022-12-22 07:52 UTC, russab0 commented on parse/delta_date.py
> +            if word1 == "полчаса":
А почему "полчаса" отдельно от всего остального?

2022-12-22 07:52 UTC, russab0 commented on parse/fix_date.py
> +    numbers = {
Давайте вынесем это в глобальные константы: NUMBERS, MONTHS, WEEKDAYS

2022-12-22 07:52 UTC, russab0 commented on parse/fix_date.py
> +    _year, _month, _day, _hour, _minute = cur_date.year, cur_date.month, cur_date.day, cur_date.hour, cur_date.minute
Почему с нижним подчеркиванием в начале?

2022-12-22 07:52 UTC, russab0 commented on requirements.txt
> +sqlalchemy
Не нужно дублировать sqlalchemy

2022-12-22 07:52 UTC, russab0 commented on update_reminders.py
> +    while 1:
while True

2022-12-22 07:52 UTC, russab0 commented on using_db.py
> +        if i.isalpha() or i in '.,)(:;"[]-_=+ ':
Лучше эту строку вынести в константу

2022-12-22 07:52 UTC, russab0 commented on using_db.py
>      msg = Message()
Нельзя ли создавать Message сразу с аргументами text, datetime, intent, user?

2022-12-22 08:28 UTC, nekstas commented on data/models/reminder.py
> +    user = orm.relation('User')
Ну да, user_id ведь для связи таблиц в БД, а user для получения объекта пользователя через `.user`

2022-12-22 08:44 UTC, nekstas commented on data/fill.py
> +    for i in file:
Опять же, может, нужны не j и i, а более осмысленные названия?

2022-12-22 08:44 UTC, nekstas commented on intents/last_news.py
> +    req = requests.get(link)
Надо бы делать асинхронный запрос, `aiohttp` в помощь)

2022-12-22 08:44 UTC, nekstas commented on intents/last_news.py
> +    newr = requests.get(url)
Тут тоже нужна асинхронность

2022-12-22 08:44 UTC, nekstas commented on requirements.txt
> +requests
После замены на `aiohttp`, `requests`, вероятно, можно будет убрать

2022-12-22 09:37 UTC, nekstas commented on intents/talking.py
> +            res.append(segm)
Может, `re.split`?

2022-12-22 09:37 UTC, nekstas commented on intents/talking.py
> +            res.append(segm)
```python
import re
res = re.split(r'@@ПЕРВЫЙ@@|@@ВТОРОЙ@@', s)
```

2022-12-22 10:35 UTC, nekstas commented on intents/talking.py
> +                    cnt_let += 1
Полезная регулярка: ` re.sub(r'[^a-zа-яё\.\,\)\(\:\;\"\[\]\-\s]', '', s, flags=re.UNICODE | re.IGNORECASE)`

2022-12-22 11:15 UTC, russab0 approved these changes

2022-12-22 11:30 UTC, merged